name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [3.7, 3.9]
        platform: [x64, win32]
        vstudio: [16]
        include:
          - platform: x64
            arch: x64
          - platform: win32
            arch: x86

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}

      - name: Install Build Deps
        run: python -m pip install wheel

      - name: Move git binary
        # Temporarily move preinstalled git to prevent errors related to cygwin.
        run: Rename-Item "C:\Program Files\Git\usr\bin" notbin

      - name: Build
        run: >
          python build.py build
          --platform=${{ matrix.arch }}
          --vs-ver=${{ matrix.vstudio }}
          --same-python
          --enable-gi
          --py-wheel
          --skip gtksourceview,emeus,clutter
          gtk3-full pycairo pygobject lz4 enchant

      - name: Restore git binary
        run: Rename-Item  "C:\Program Files\Git\usr\notbin" bin

      - name: Zip Bundle
        run: >
          7z a
          ${{ github.workspace }}/${{ env.release_name }}.zip
          "C:\gtk-build\gtk\${{matrix.platform}}\release"
        env:
          release_name: "gvsbuild-py${{ matrix.python }}-vs${{ matrix.vstudio }}-${{ matrix.arch }}"

      - name: Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          body: gvsbuild-${{ steps.date.outputs.date }}
          files: "*.zip"
