name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [3.9]
        platform: [x64, x86]
        vs_ver: [16]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: wingtk/gvsbuild
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.platform }}

      - name: Install Build Deps
        run: python -m pip install wheel

      - name: Move git binary
        # Temporarily move preinstalled git to prevent errors related to cygwin.
        run: Rename-Item "C:\Program Files\Git\usr\bin" notbin

      - name: Build
        run: >
          python build.py build
          --platform=${{ matrix.platform }}
          --vs-ver=${{ matrix.vs_ver }}
          --same-python
          --enable-gi
          --py-wheel
          --skip gtksourceview,emeus,clutter
          gtk3-full pycairo pygobject lz4 enchant

      - name: Restore git binary
        run: Rename-Item  "C:\Program Files\Git\usr\notbin" bin

      - name: Zip Bundle
        run: >
          "C:\Program Files\7-Zip\7z.exe" a
          ${{ github.workspace }}/${{ $env.release_name }}.zip
          "C:\gtk-build\gtk\${{matrix.platform}}\release"
        env:
          release_name: "gvsbuild-py${{ matrix.python }}-vs${{ matrix.vs_ver }}-${{ matrix.platform }}"

      - uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: ${{ github.workspace }}/gvsbuild*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
